name: scivistutorial
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipython
  - vtk
  - paraview
  - yt
  - mayavi
  - ipyvolume
  - spyder
