name: scivistutorial
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib>=2.0
  - pyqt>=5.9
  - vtk>=8
  - jupyter
  - ipython
  - mayavi
  - yt
  - ipyvolume
  - spyder
