name: scivistutorial
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - matplotlib>=2.0
  - vtk>=8
  - jupyter
  - ipython
  - mayavi
  - yt
  - spyder
  - scipy
  - pyqt
  - ipyvolume
